# -*- coding: utf-8 -*-
"""iris_clustering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TN9LzlyZEZ6XoInNfmb4kYlUzWLoZ9e5
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
# %matplotlib inline

from sklearn.cluster import KMeans

df = pd.read_csv('Iris.csv')

df.head()

df.info()

df.isnull().sum()

df.drop(["Id"],axis=1,inplace=True)

df.head()

a=df.iloc[:,[0,1,2,3]].values

wcss=[]
for i in range(1,11) :
  model1=KMeans(n_clusters=i,init="k-means++",random_state=0)
  model1.fit(a)
  wcss.append(model1.inertia_)

plt.plot(range(1,11),wcss)
plt.title("Elbow Method")
plt.xlabel('No. of clusters')
plt.ylabel('WCSS')
plt.show()

model2=KMeans(n_clusters=3,init="k-means++",random_state=0)

b=model2.fit_predict(a)

species=df.iloc[:,df.columns=='Species']
species

plt.scatter(a[b == 0, 0], a[b == 0, 1], s = 75, c = 'purple', label = 'setosa')
plt.scatter(a[b == 1, 0], a[b == 1, 1], s = 75, c = 'blue', label = 'versicolour')
plt.scatter(a[b == 2, 0], a[b == 2, 1], s = 75, c = 'pink', label = 'virginica')
plt.scatter(model2.cluster_centers_[:, 0], model2.cluster_centers_[:,1], s = 75, c = 'black', label = 'Centroids')
plt.legend()

